baseURL = "https://mehrdaddw.github.io/myblog/https://mehrdaddw.github.io/myblog/"  # Adjust for your repo
languageCode = "en-us"
title = "Void Visions"
theme = "paper"

[params]
  color = "linen"  # Optional: theme style
